---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ansible-vault-password-backup
  namespace: semaphore
spec:
  encryptedData:
    vault_password: AgCW8UUHj1ATKn2QiSI0i367cAsgWe0aUyA9lbkZa3Y4rot8seHgWJfxadJLe4bZZ6xIcjhOXt90wmkObKcdesWgsHR8Kvsmoz5rQNPiXuyov05jE6hOLuDU+ArxxN//Uaw5y3EZf5q7gPDQOaMozR3hf8sncK2rnv7/6c61/ITNViuDWIul+PrcevWeDnfMUqjM45DZjEPqk1rGhyhM/xJQogcSVXAyzLz1otHCBQPy/zD2jsKfzgMsTL8x4WIrRD7g4WeUA0vvqrRbe2nJI6asnoJqXJVNArb1dYiPC0bx7XGsvsGWhQUonvo5NyvezxPKX029cFazXlartpI0kM/rS5jC4+QnIpEJl4t0yZRhFt46NTV84Oev7EpLycrR9+GeXh3SOdNIys8sdEJi0rT8JKPO2PbqYT9ES5L05HIFSP8HYcO1LcVGwOQZ5cXdD7WnSDC0gwBLnDFxOrzexGN2LgIYxyUg3b4l6rw11imtMd78HE4hm8QjhNGPOGXgIqYHYhWGGVa8I0upml1CB7aBKNEUsHQnXcKvmeTsdGJgX6zaJ21Ug5Vvkhl6GhojS3xHAy/khdtbeEcVAKLl4cBFHeUIoZItmH0ATHlLGJ08gMOrEI5Hgu4fF1oAyXY9pe6XsiNwYmtyH1FYR080+UUBN/cZ0DnKIeIh4vkMe0gnpKSAyntOHOlxyZv06aav2eHYmejHxo/8
  template:
    metadata:
      name: ansible-vault-password-backup
      namespace: semaphore
    type: Opaque
