---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: semaphore-admin
  namespace: semaphore
spec:
  encryptedData:
    SEMAPHORE_ADMIN_PASSWORD: AgDHg56Vt/OiwMthswioaT/MRg/HWcdgnyiUzYQQFw+JdgOzeC0ox8jSAJGTDInMc2yVwEm1NSvtbBMq5qvJZcBnW30L/fM623zSMsakWA5JBAEpZUa0inTwhNtQxccZIiA2ubJTFKHMFGZtc8un/Bg4IQ1hjWgJnCUIBuJgyXGxJ3Zx4tHSh7vTM6ojAI64N4gdxia+3tqbYzGb3JHobP9oLByQC2C89vbFLP3ovLDvcNaOn1rMVbz8wqduJw5DslUh0qTKwFHB5Q4YEchP8FNZEaTj9PolGd1eDLYO2OeTEoW3TIDBFy0fo0mfICo/2jXWqo9XRKgpYWAioAdrHuz5BKBz3+Hyd/ta8Smw723rvceob3WOsvyrs2iPh7l/oPfdvda2dfB0Hr7jtqeEZli4qR1rtmDWSEhadzF9OTc4CqRnrVfrCCEjkRxRpbsvkEYEZs7QRJY+W8uitFch+czcwAg3KrUFbte26nDAy6dRgFABsBQZES+QhNuvR7R7VWfJbh2g2ydytruaaNL1wNF68LnHmnuFuULQTgphITKcDB1yKqRV+eR4xbgHb4/ngEMArWI8U16nzTPt8vd/FaVAz4s0KRh1lCS5KUtAE4haMD+OcJ8fSpiWnbH1ImES9CeSLg4fIyp/VOJI+0vCguxDSlvebIKsQ/dINDLqEA1h8Jjpx6eJ+tQetENr05OHwC4gbq5nLOQh
  template:
    metadata:
      name: semaphore-admin
      namespace: semaphore
    type: Opaque
