---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: semaphore-enc-key
  namespace: semaphore
spec:
  encryptedData:
    SEMAPHORE_ACCESS_KEY_ENCRYPTION: AgBpD9LD2qYgKiK8uKl4Smd/yqWSZGYrV7KAT4Ul8cdKkYoRPWxjDOedQU0eSotDpoAE9rSFmOyp8waKJkvONyyelLomAXLT4T3mY/14mAAWFLcpFTflbU83GLM4V7RhnKq44vaLQpkAAiqZvw9Z5NH/CRSVhl+8jsRepksGkhklOwPqSqKNe2c/j/VPNwgSa+Nh6+gMAvISaVH0Cwu/p1fnx6uqb9IeWHwZhznPdFwQjaJXWxqWjeKT0jBxi3Sb8k//dJmsXQNRgzPYm2OnPYoWDZ5CLcmV+Ouuqpj5dzE8tgi4o8dpf+iP2DgLWguZjTP6g1SNPmkjHVr08KZhuuPFGSLdfvtrOXDQWCHDU6speqh7cCHipPiZdwLLKWkBDD/0YOzs/mE31zbLTaF5OgTzOledvlCTiTHmEw2klI2TRbc+t/+iWRDGpJUzyIi7PaJhehmP49u3P7Ud8tqMUMAETnMWftCDP1F0h222r5gcz0Tf4LFp/FF38M1E2hMnnn712rQkA3weyDTT5F8OA827YXK1mk2CdCemMxyZAIjRUMboZvcn08uOtEFiJkw9xCYEtQtcZ/sTxPeiBd2yTYdnovzJnMqvNstw2E1Q59B2xggWpIz6qijrZmIIwJlwCzmtVHex3VAaEFe5GlHnELE7k6ABU6O/vMseY4T9bUNQFKCoybJMU18FSXTYw9xD94MLPzxGXtzXKbPrNyJvKq3DHAmPGzxe9DE1PJOlPUW4I7lRGW7JNq5qUOJ1Pw==
  template:
    metadata:
      name: semaphore-enc-key
      namespace: semaphore
    type: Opaque
