---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: semaphore-db
  namespace: semaphore
spec:
  encryptedData:
    SEMAPHORE_DB_PASS: AgDEF1oj8WXGSyQ+zh6as/G5qid8zw7umA9gziiHiu8+skQboeUW12iS7opyMYypM1UnSMED6Em92MtUI/78VuGKfNal6Di96xv5iLUiwQKfr+oSmgmtgRODgfS7mdvkJJJz8I4F02GtBcW7cSmoviq0blFVk05PvKFsr+nFnFH1hfEvFspA5ozki2GRcjMtAwuqI6ug0NnpYmwp/Kef9+B8W7oRfwgqDaP0/Vjkih8NybHQCBRws2Hn9UmmRD5aNU//+AuvSWjfid7a/CtAadZ/y6zTKCLB0Osx6YXoQk0+4iFpBlImcCUQdChCTHb/jUBOMHrwAMM2u7Nal1enDnsmWrQ8FsrcLwHgtDUpCWjaJUkMm/RM5CpxwDWQograHoYs+9jS0LZAGr/Vhuyru0iymCNDHI8GebJ86LnnZXpJ03LQnFIPhOODTrmJF+JBJ1LxwUqEyo8cW6E8teLyxJwTC8zTLGlF/75qPjvQ0RAzI2sweSbhErgxMwoo8S/Wbnk5NjcUkhMl5YItRIFETd4z+6mwyzJr1W3ROXR9/wa8ONTYvB+x1UwyXkhPG8pJMOUnRtLDfSae6wFhd+KYX15XK2oitoAhhF57hG2/6j/yTDKjB3ZVUZY5Ak4NiCjejvJm9KyA5raUWPcH1q6kn0q/qZj4kP6zeGhJurQ9Ie/7qPs16vkNKM2+OtoZoB4z8BFiQbpBcBBx
    SEMAPHORE_DB_USER: AgCG7e8A7rAPaVqnFBRMsm0qGuHM2zMZLoyBAbQUDOF6YVA4NILbYVKSVs23GaOBfWYsTcwICZs9rBompOI/iLSPqCrLzu/G6QWoMV3asF86T4yYy2EMvUlo0jnlkQg2LttYXsgoncH3EEVwIQo3UrJPdlFhHdzOyqbMTosSniYxjwOqh6mejCwCqcOgj6lVc+VxahUD++SrWfvaB0wlWqZdu5VWq9fpD2GYojhUETHWwdNt3t1Vsnq65Lj9CBys2znKh9j4xuY4vX8eA2cjJnTakavfkFa1FJO4i1MjglZWjJbUmZHAurzNzR0Tfzv46vMZySIaKYUaXNQsr8WRrfvwRTHcuuDSFOrfas5thIxwpLvebe1Gkji/mcm8iJk4jQeBmG2v6zf3f+zfUMRXaWToYgZkjQvjiFQtY+MVVQ20lN7clr6Slo42mD0/MxnYEZmKCmz9EJKeWTgfVo5uSPUj/Z341U4sNF0vBWBq3ZPXMV/kUnfLt9WUYw4WO//Kxk3ZpCP3DgSATtl7t4sr3uH0VwOsJ4dQD30tJ0hdIrRNwneZc8lKQW06A2+/SVYtRhtvY70e7/B7kznWfg1CZRuQ2Sy2OV9mq1LkarH/66bYJ3NFKh4ldGXpNM+FAEx42GdaRHE5QteAfHmCVdMzKJNkdavbn/+1iBbp2NzQqnh8GX0dTgwUhAErpGGQIUU7Hm+hjm3ueIf7UtM=
  template:
    metadata:
      name: semaphore-db
      namespace: semaphore
    type: Opaque
